service: chois-english-back
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  app:
    handler: app.index
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3001
